/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/living-room/sofa.glb --transform --shadows -o components/scenes/living-room/Sofa.tsx 
Files: public/models/living-room/sofa.glb [36.42MB] > /Users/feifeifei/Workspace/stranger-things-3d-rooms/components/scenes/living-room/models/living-room/sofa-transformed.glb [3.89MB] (89%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    model: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/living-room/sofa-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.model.geometry} material={materials.model} />
    </group>
  )
}

useGLTF.preload('/models/living-room/sofa-transformed.glb')
